loss_params:
  loss: ['cls-so', 'proto-each', 'I2C-cross', 'semi-condentmax', 'semi-entmin', 'tgt-condentmax', 'tgt-entmin']
  pseudo: True
  T: 0.05
  thres_src: 0.98
  thres_tgt: 0.98
  temp: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  weight: [1, 1, 1, 0.5, 0.05, 0.5, 0.05]
  start: [0, 0, 0, 0, 0, 0, 0]
  end: [1000, 1000, 1000, 1000, 1000, 1000, 1000]
  m: 0.5
  k: []
data_params:
  fewshot: '1'
  name: office  #'office'
  source: 'amazon' # 'amazon'
  target: 'dslr' # 'dslr'
  aug: 'aug_0'
  image_size: 64 # 224
  aug_src: 'aug_0'
  aug_tgt: 'aug_0'
  train_val_split: []
  num_cls: 31
clus_params:
  kmeans_freq: 1
  type: ['each']
  n_k: 15 
  k: [31, 62] 
  n_kmeans: 30 
  tgt_GC: []
optim_params:
  batch_size: 16
  learning_rate: 0.01
  conv_lr_ratio: 0.1
  patience: 20
  decay: True
  weight_decay: 0.0005
  cls_update: True
  momentum: 0.9
  nesterov: True
  lr_decay_rate: 0.1
  lr_decay_schedule: []
ex_params:
  path: './temp/resnet18-5c106cde.pth'
  T_max: 30
  epochs: 30
  eta_min: 0.000001
  lr_scl: 0.00001
  lr_ce: 0.1
  wd: 0.0001
model_params:
  out_dim: 128 #512
  version: 'pretrain-resnet50'
  load_weight: 'src-tgt' 
  load_weight_thres: 20
  load_weight_epoch: 2
  load_memory_bank: True
num_epochs: 500
ce_epochs: 10
steps_epoch: False
cuda: True
gpu_device: [0]
debug: False
pretrained_exp_dir: False
continue_exp_dir: []
summary_dir: './test/temp/experiments/office/amazon_to_dslr/summaries/'
checkpoint_dir: './test/temp/experiments/office/amazon_to_dslr/checkpoints'
out_dir:  './test/temp/experiments/office/amazon_to_dslr/out/'
log_dir: './test/temp/experiments/office/amazon_to_dslr/logs/'
validate_freq: 1
copy_checkpoint_freq: 50
k_list: [31, 62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 
        62, 31, 62, 31, 62, 31, 62, 31, 62, 31, 62]